version: "3.8"

services:
  gateway:
    build:
      context: .
      dockerfile: ApiGateway/CapstoneReviewSlot.Gateway/Dockerfile
    ports:
      - "5000:80"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
