// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registration.Infrastructure.Persistence;

#nullable disable

namespace Registration.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RegistrationDbContext))]
    [Migration("20260422132252_InitRegistration")]
    partial class InitRegistration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Registration.Domain.Entities.StudentSlotPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PreferenceId");

                    b.Property<Guid>("CapstoneGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PreferenceOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("ReviewSlotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentMssv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CapstoneGroupId", "ReviewSlotId", "StudentMssv")
                        .IsUnique();

                    b.ToTable("StudentSlotPreference", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
